### PR TITLE
Using patterns

### PR DESCRIPTION
**Pull request by FeelTheLemon**
In each gamemode info.txt contains fretta_maps section with **patterns**, so we need to use them, not just trying to slice start of map name.

### CODE REVIEW

**Comment by JetBoom** [comment]
This could be a breaking change so no.

**Comment by FeelTheLemon** [comment]
This will not break anything. Tested!
According to [old wiki](https://maurits.tv/data/garrysmod/wiki/wiki.garrysmod.com/index4d52.html) and [new wiki](http://wiki.garrysmod.com/page/Gamemode_Creation) map list in info.txt contains **patterns**, not just strings. 

`string.match(mapname, p)` will always match map string and map pattern like "deathrun_" or "^deathrun_",  but this also give the ability to use patterns like "mg_\*smash\*" or something like that.

`string.sub( mapname, 1, #p ) == p )` will **only** match map if pattern looks like this: "^deathrun_", even "deathrun_" does not works right now.

**Comment by JetBoom** [comment]
That's the gmod wiki not the fretta wiki.

breaking case:
map called eft_somethingmg_ will appear on a gamemode that uses "mg_" as one of its entries.

**Comment by FeelTheLemon** [comment]
Yes, but you need to use `^`, and what with "mg_\*smash\*" ?

**Comment by JetBoom** [comment]
Nobody uses ^ because it's been the way it is for years. No one is changing their gamemodes for semantics.

**Comment by FeelTheLemon** [comment]
First of all, fretta is a Garry's Mod gamemode, so gmod wiki is fretta wiki.

Nobody uses ^ and patterns, really? Then take a look at:
- sandbox/sandbox.txt
- terrortown/terrortown.txt
- just every mod in [fretta archive](https://github.com/glua/gm-fretta-archive)
- [FreezeTag](https://github.com/NiandraL/FreezeTag-Fretta-/blob/master/gamemodes/freezetag/freezetag.txt)
- [Poltergeist](https://github.com/NiandraL/Poltergeist-Fretta-/blob/master/gamemodes/poltergeist/poltergeist.txt)

**Comment by JetBoom** [comment]
> fretta is a Garry's Mod gamemode, so gmod wiki is a fretta wiki.
that's not how things work.

All gamemodes using fretta13 as a base use the current system. It's not getting changed, no matter how many 4 year old gamemodes you show me.

**Pull request closed without merging**
